### ISSUE TITLE
consider making eye-tracker optional

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#15]
in `createFilename.m`

**Comment by marcobarilari** [comment]
As mentioned in #14, ET is already optional. An argument could be that at the end of the day using the CPP_*** packages will carry a good amount of dead code in your experiment scripts. But that is what, hopefully, will make it flexible for different experiments. 

On that, I am preparing a `WIP canvas scripts folder` for the experiment to come that will have all the code required to use the CPPs pacjages.

**Comment by Remi-Gau** [comment]
We can close this, no? This is not taken care of by the checkCFG, no?
