### ISSUE TITLE
consider making subjectGrp optional

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#16]
in `createFilename.m`
at the current state, in `userInput` function I can leave the group part empty but then in createFilename gives error that 
`Reference to non-existent field 'subjectGrp'`

**Comment by Remi-Gau** [comment]
made a quick fix:
`[expParameters] = userInputs(cfg, expParameters, askGrpSess)`

if you use it with `askGrpSess = [0 0]`
it won't ask you about group or session

if you use it with `askGrpSess = [1]`
it will only ask you about group

if you use it with `askGrpSess = [0 1]`
it will only ask you about session

if you use it with `askGrpSess = [1 1]`
it will ask you about both
this is the defaut

**Comment by CerenB** [comment]
Cool! would it be good to embed this variable into `expParameters` `struct`?

**Comment by Remi-Gau** [comment]
That's possible. 
As a user you would prefer that option?

**Comment by CerenB** [comment]
I was thinking I'd define `askGrpSess = [0 0]` in `getParams` script instead of the `mainExp`. (to keep changeable things in `getParams`). So in order to carry `askGrpSess` back to `mainExp`, I'd use it in `expParams` structure.

**Comment by Remi-Gau** [comment]
Makes sense. 
Will make the change. :-)

**Comment by Remi-Gau** [comment]
This should be fixed now. :-)
