### ISSUE TITLE
[ENH] defining levels as objects 

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#169]
_You think / need this code to do_ is creating event.json files to pass the bids-validator. 

_That means that we can improve the code or the documentation._

_Tell us more about it below._
At the current form, the cpp-bids creates event.json files but due to the latest changes in the bids-validator, the validator is not happy. It gives the below error : 
```
File Path: Invalid JSON file. The file is not formatted according the schema.
    Type:       Error
    File:       sub-001_ses-001_task-RhythmBlock_run-001_events.json
    Location:       raw/sub-001/ses-001/func/sub-001_ses-001_task-RhythmBlock_run-001_events.json
    Reason:     Invalid JSON file. The file is not formatted according the schema.
    Evidence:   ['trial_type'].Levels should be object

```
The easy way is to add some curly brakets somewhere, just couldn't find in which function to make that change, yet!

**Comment by Remi-Gau** [comment]
Fixed by 
https://github.com/cpp-lln-lab/CPP_BIDS/pull/168/commits/bbf21e73849bc162704165f82f38ba77d3f93d6d
