### ISSUE TITLE
save stim file

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#17]
is it possible to create two different output file? e.g. `.tsv file for stimulus` and `.tsv file for tapping`

**Comment by Remi-Gau** [comment]
like one with stimulus and the other for the responses (is that what you mean by tapping?) ?

**Comment by CerenB** [comment]
yes, since not in every stimulus participant will press. so i want to keep these two separated. but I guess the function is doing it... though I'm not sure. Definitely a better readme could have made my day easier :D

**Comment by Remi-Gau** [comment]
yes I need to give more explanation there.

but your approach is definitely possible and some of the code can be reused for that purpose.

let me check if there is a way to make that even fit within the BIDS framework.

**Comment by Remi-Gau** [comment]
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/06-physiological-and-other-continuous-recordings.html

Physiological and other continuous recordings

Template:
```
sub-<label>/[ses-<label>/]
    func/
        <matches>[_recording-<label>]_physio.tsv.gz
        <matches>[_recording-<label>]_physio.json
        <matches>[_recording-<label>]_stim.tsv.gz
        <matches>[_recording-<label>]_stim.json
```
Optional: Yes

Where <matches> corresponds to task file name without the _bold.nii[.gz] suffix. For example: sub-control01_task-nback_run-1. If the same continuous recording has been used for all subjects (for example in the case where they all watched the same movie) one file can be used and placed in the root directory. For example:task-movie_stim.tsv.gz

**Comment by Remi-Gau** [comment]
Would it make sense to use the `_stim.tsv` option in your case?

**Comment by CerenB** [comment]
maybe I should open a new issue but does it say anything regarding to `duration` for behavioral exp? 
In `saveEventFile.m` there's `duration` to be saved but what is it?

**Comment by Remi-Gau** [comment]
duration is just how long each event was : for responses I would put 0

**Comment by CerenB** [comment]
OK! so I shall define `duration = 0` in my main script and then call `saveEventsFile` function. 
Then `_stim.tsv` sounds ideal. How shall I implement that?

**Comment by Remi-Gau** [comment]
Will open a pull request and let you review it: does that make sense?

**Comment by CerenB** [comment]
sure!

**Comment by CerenB** [comment]
I think so far the changes were made was on `createFilename.m` but maybe for a cleaner logging of the behavioral experiment(s), I might need some changes in `SaveEventFile.m`. such as if in `beh` modality, `duration`  and `onset` could be done optional.

**Comment by Remi-Gau** [comment]
I think that for the events file to be BIDS compliant we might need to keep the duration and onset columns, but I could check if the it is still OK to fill them with N/A or NAN.

**Comment by CerenB** [comment]
OK!

**Comment by Remi-Gau** [comment]
repoening to remind me I need to improve the doc so that @CerenB suffering was not in vain

**Comment by CerenB** [comment]
To save `_stim.tsv` and `_event.tsv` separately, I think i need to have some additional lines in `saveEventFile.m` no?
it seems at the current stage, only it saves with `_events`

**Comment by Remi-Gau** [comment]
let me check

**Comment by Remi-Gau** [comment]
hum... a clean solution won't be quick but let me write a bit of code that should do the trick for now.

**Comment by Remi-Gau** [comment]
OK the quick fix is this:

```
% create file for stim a returns its file ID that will be stored in stimFile.fileID
stimFile = saveEventsFile('open_stim', expParameters, []);

% compared to 
% create a file for events a returns its file ID  in logFile.fileID
logFile = saveEventsFile('open', expParameters, []);

% you can the add 'evetns' as usual and then use save by passing stimFile instead of logFile
saveEventsFile('save', expParameters, stimFile);
```

**Comment by Remi-Gau** [comment]
I have update the function and this should work now
