### ISSUE TITLE
lower case in saveEventFile

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#18]
is it compulsory for BIDS? If yes, then nothing can be done, I see. But if it's not having small letters all the way through does not help to read variables in logfile.

**Comment by Remi-Gau** [comment]
you mean in the 'fields names', right?

**Comment by CerenB** [comment]
yes, I thought in the title- header of the file they could be however the user wants them to be?

**Comment by Remi-Gau** [comment]
you might be right: I think that the only restrictions are for the `trial_type`, `duration`, `onset`.
not sure that it applies to whatever else the user puts in there.
Need to double check.

**Comment by Remi-Gau** [comment]
nothing in the specs mentioned that things have to be lower case. fixing it now.
