### ISSUE TITLE
cannot save cell input

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#20]
In `SaveEventFile.m`, I cannot save cell array. Is there a solution or suggestion for this?
 ```
Error using fprintf
Function is not defined for 'cell' inputs.

Error in saveEventsFile (line 86)
                    fprintf(logFile(1).eventLogFile, '%f\t', data);

Error in tapMainExperiment (line 102)
        saveEventsFile('save', expParam, currSeq, ...
```

**Comment by CerenB** [comment]
I sort of understood the issue. I'm making a structure 80 x 9 (with ch or floating numbers) and want to save some fields in this structure. Since `eventLogFile` is also in this structure, it automatically created as a column with 1 row of scalar value but the rest is empty `[]`.
Basically, I thought I should put everything into 1 structure to call for `saveEventFile.m`

**Comment by Remi-Gau** [comment]
yeah that is the way I went with.

one structure and the fields mention the name of the columns to be added to the logfile.

I need to expand the help section of that function. Sorry. :'-(

**Comment by CerenB** [comment]
OK, I temporarily fixed things in my exp.  One thing remains. 
I record at the end of the event (which is 3min!). When I call `saveEventFile.m` I have a `struct` full of 80 rows with `fields`. However, the function saves only 1 row of this `struct`

**Comment by Remi-Gau** [comment]
hum... It is not meant to do that.

The unit test runs like this and saves the 2 events in one go with no loop.

```
logFile(1,1).onset = 2;
logFile(1,1).trial_type = 'motion_up';
logFile(1,1).duration = 1;
logFile(1,1).speed = 2;
logFile(1,1).is_fixation = true;

logFile(2,1).onset = 3;
logFile(2,1).trial_type = 'static';
logFile(2,1).duration = 4;
logFile(2,1).is_fixation = 3;

saveEventsFile('save', expParameters, logFile, 'speed', 'is_fixation');
```

**Comment by CerenB** [comment]
yup!
