### ISSUE TITLE
creating unasked folder

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#27]
it might be my issue, will check but now the code is creating `eyetracker` folder in addition to beh folder.

**Comment by Remi-Gau** [comment]
hum...
Will cross check if I have not left a 
`cfg.eyeTracker = true;`
lying around

**Comment by Remi-Gau** [comment]
yup there is a bug: will troubleshoot.
thanks for spotting this

**Comment by Remi-Gau** [comment]
should be fixed now
you just need to pull from the master branch.
