### ISSUE TITLE
userInput need else condition for subjectGrp variable

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_BIDS#36]
```
if askGrpSess(1)
        subjectGrp = lower(input('Enter subject group (leave empty if none): ', 's'));
    end
```
At the moment, outside of debug mode, there's no `subjectGrp` assignment if `askGrpSess =0`. So the script crashes there.

**Comment by Remi-Gau** [comment]
woopsy

Will try to look into this ASAP

**Comment by CerenB** [comment]
oh no! I inserted a temporarily fix in my scripts. So no need for "asap" at least from my side.

**Comment by Remi-Gau** [comment]
>  So no need for "asap" at least from my side.

Best thing I have heard so far today. :smile: :heart: :rocket:

**Comment by Remi-Gau** [comment]
@CerenB when you have time can you check if the PR #41 fixes this issue.
