### ISSUE TITLE
reuse spm_mkdir and spm_copy to facilitate creating and copying BIDS dir hierarchy

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS#58]
https://en.wikibooks.org/wiki/SPM/BIDS

**Comment by marcobarilari** [comment]
Does this mean that spm will become a dependency?

**Comment by Remi-Gau** [comment]
hell NO!

we just grab those fucntions from spm and rewrite them to make them stand alone.

**Comment by Remi-Gau** [comment]
closing this as this is being integrated in bids-matlab
