### ISSUE TITLE
Create a binder for demo

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_BIDS#61]

**Comment by marcobarilari** [comment]
I like this idea!!

**Comment by Remi-Gau** [comment]
Adding some of the links from Agah's repo at the brainhack that we could reuse to make our life easier for setting up.

https://github.com/agahkarakuzu/eda_organized/tree/master/notebooks
https://github.com/agahkarakuzu/eda_organized/tree/master/binder
https://github.com/agahkarakuzu/eda_organized/tree/master/Deploy/Docker/BRAINHACK20
https://github.com/agahkarakuzu/eda_organized/blob/master/.github/workflows/buildDocker.yml


Guillaume also had set up a binder for bids-matlab
https://github.com/bids-standard/bids-matlab/tree/master/binder

And even one for SPM
https://github.com/spm/spm-notebooks
